# Generated by Django 5.2.8 on 2025-11-15 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('config', models.JSONField(blank=True, help_text='Configuración específica del corredor', null=True)),
            ],
            options={
                'verbose_name': 'Corredor',
                'verbose_name_plural': 'Corredores',
            },
        ),
        migrations.CreateModel(
            name='ArchivoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre_original', models.CharField(max_length=255)),
                ('ruta_almacenamiento', models.CharField(help_text='Path o URL donde se guardó el archivo', max_length=500)),
                ('tipo_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('estado_proceso', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('ok', 'Procesado OK'), ('error', 'Procesado con errores')], default='pendiente', max_length=20)),
                ('resumen_proceso', models.JSONField(blank=True, help_text='Resumen de registros OK, rechazados, etc.', null=True)),
                ('errores_por_fila', models.JSONField(blank=True, help_text='Detalle de errores por fila', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tiempo_procesamiento_seg', models.FloatField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_carga_enviados', to=settings.AUTH_USER_MODEL)),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='calificaciones.corredor')),
            ],
            options={
                'verbose_name': 'Job de Carga',
                'verbose_name_plural': 'Jobs de Carga',
            },
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('identificador_cliente', models.CharField(help_text='RUT, documento, ID cliente, etc.', max_length=100)),
                ('instrumento', models.CharField(help_text='Acción, bono, fondo, etc.', max_length=150)),
                ('moneda', models.CharField(default='CLP', max_length=10)),
                ('factor_8', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('factor_9', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('factor_10', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('factor_11', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('factor_12', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('factor_13', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('factor_14', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('factor_15', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('factor_16', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('factor_17', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('factor_18', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('factor_19', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('archivo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_generadas', to='calificaciones.archivocarga')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='calificaciones.corredor')),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
            },
        ),
        migrations.CreateModel(
            name='HistorialCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('accion', models.CharField(default='actualizacion', max_length=100)),
                ('descripcion_cambio', models.TextField()),
                ('datos_previos', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('cambios_resumen', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='calificaciones.calificaciontributaria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_calificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Calificación',
                'verbose_name_plural': 'Historial de Calificaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_iso3', models.CharField(help_text='Ej: CHL, PER, COL', max_length=10)),
                ('reglas_tributarias', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'unique_together': {('nombre', 'codigo_iso3')},
            },
        ),
        migrations.AddField(
            model_name='corredor',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corredores', to='calificaciones.pais'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='calificaciones.pais'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='pais_detectado',
            field=models.ForeignKey(blank=True, help_text='País detectado automáticamente a partir del archivo/origen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_detectadas', to='calificaciones.pais'),
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='calificaciones.corredor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['corredor', 'identificador_cliente'], name='calificacio_corredo_3983b6_idx'),
        ),
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['pais'], name='calificacio_pais_id_2eafbc_idx'),
        ),
    ]
