# Generated by Django 5.2.8 on 2025-12-01 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivocarga',
            options={},
        ),
        migrations.AlterModelOptions(
            name='calificaciontributaria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='corredor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historialcalificacion',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuarioperfil',
            options={},
        ),
        migrations.AlterField(
            model_name='archivocarga',
            name='errores_por_fila',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivocarga',
            name='estado_proceso',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('ok', 'Ok'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='archivocarga',
            name='resumen_proceso',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivocarga',
            name='ruta_almacenamiento',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='archivo_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_generadas', to='calificaciones.archivocarga'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='identificador_cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='instrumento',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='pais_detectado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_detectadas', to='calificaciones.pais'),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo_iso3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='corredor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='calificaciones.corredor'),
        ),
    ]
