# Generated by Django 5.2.8 on 2025-12-04 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_alter_archivocarga_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='corredor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='calificaciones.corredor'),
        ),
    ]
