# Generated by Django 5.2.5 on 2025-12-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_alter_usuarioperfil_corredor'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivocarga',
            name='mercado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='archivocarga',
            name='periodo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivocarga',
            name='tipo_carga',
            field=models.CharField(choices=[('FACTOR', 'Carga por factor'), ('MONTO', 'Carga por monto')], default='FACTOR', max_length=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='ejercicio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_actualizacion',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='mercado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='valor_historico',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='corredor',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
