# Generated by Django 5.2.5 on 2025-12-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_archivocarga_mercado_archivocarga_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='dividendo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='isfut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='secuencia_evento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
