# Generated by Django 5.2.8 on 2025-12-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0005_calificaciontributaria_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='valor_actualizado',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True),
        ),
    ]
